services:
  postgres:
    image: postgres:17-alpine
    env_file:
      - ./configs/local.env
    environment:
      POSTGRES_USER: ${DB_CONFIG_USER}
      POSTGRES_PASSWORD: ${DB_CONFIG_PASSWORD}
      POSTGRES_DB: ${DB_CONFIG_DBNAME}
    ports: ["5432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data
    #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U golang-template-service"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:3.7.0
    env_file:
      - ./configs/kafka.env
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8090:8080" # Будет доступен по адресу http://localhost:8090
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: "true"

  producer-api:
    build: .
    env_file:
      - ./configs/local.env
    command: ./producer -service=users
    ports: ["8080:8080"]
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BROKER=kafka:9092

  consumer-worker:
    build: .
    env_file:
      - ./configs/local.env
    command: ./consumer -mode=users
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BROKER=kafka:9092
      - DB_CONFIG_HOST=postgres

volumes:
  pg_data:
